config/routes.rb
Pjax::Application.routes.draw do

  root :to => 'root#index'

  resources :products
  resources :baskets

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :basket_id, :desc, :name
  belongs_to :basket
end

app/models/root.rb
class Root < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController


  def update

  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    if session[:basket_id]
      @basket = Basket.find session[:basket_id]
    else
      @basket = Basket.create
      session[:basket_id] = @basket.id
    end
    @products = Product.find :all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/baskets/update.haml
%p
  shalaa

app/views/layouts/application.haml
!!!
%html
  %head
    %title Pjax
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = Random.new_seed
    #main{"data-pjax-container" => ""}
      = yield

app/views/root/index.haml
%p= Random.new_seed
%p= @basket.id

= link_to "regular get link", root_path
- @products.each do |product|
  %ul
    %li
      = link_to product.name + " - " + product.desc, basket_path(@basket.id, product.id), :method => :put